version: "3"
services:  
  traefik:
    image: "traefik:v2.9"
    restart: always
    environment:
      - TZ=Europe/Brussels
    ports:
      - "80:80"
      - "443:443"
      # - "8080:8080"
    volumes:
      - "./traefik:/etc/traefik"
    networks:
      - traefik

  whoami:
    image: "traefik/whoami"
    restart: always
    networks:
      - traefik

networks:
  traefik:
    name: traefik